### ISSUE TITLE
security issue while updating a user ?

### ISSUE THREAD

**Issue by Jibus22** [Jibus22/ft_transcendence#13]
https://github.com/Jibus22/ft_transcendence/blob/54fcb60bf0062e763caf83fa53d1d0f4a9d62166/back_end/src/modules/users/service-users/users.service.ts#L77-L84

If we pass `{ -id : "fake-uuid"}` to this, according to my tests in `PATCH /game/:id` it would work, so the uuid of the targeted user will change whereas we don't want that. Using a dto prevents this issue

**Comment by Jibus22** [comment]
Je passe par ici pour tester le système d'issues github :)

**Comment by 42f** [comment]
oh.. this is bad. 
Je vais fixer ^^

**Comment by 42f** [comment]
fixed by #64043881ece41513e49b159c1de60546493f61b5
